datasource:
 Ec2:
  strict_id: false
ssh_pwauth: no
users:
  - name: user
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC49R9ghBw1UjhnEakIbk3m4gR8TkQg8yDTsz8JjThSd6pfnWU3JFDNw/b19J8MP9GylmP0n7ih/BsfnLvMs2L+zXVtADE7ZavNuMaURY56gfpbb1/GQJTg+qucabWnWMx+Qwbv2PaeVIg4ijXHNkxyUNJLUA8jnVLE2Bm6CLPvhQzMaQ2rElj8zMwtJdVCf108YY3H4ksL9zp08AzLv+LdvYq6G8ZOK7Tt1FUwpj8TqAYGCihWd/8uNNpbFLd4Y3709c1p1vU7MEEbE+2J7X1R56ibIyKfX1OKYxL6lmQr5dq/An9jKv+IpS8K9X1CMzXgjabf5tFvdszsydIRpP7s2lMsUf5gwbrLi2WSH/h92V4vYUd135aZkc7Dps8Ax/Rde2mqL9YMxHPqD2rsOzgJ3d8fJ2AH04xsW1MlRs1z5YKfDKP9gj+osqSd3gLXXOhuVAfDRHAv1MCE8X9ITPsYSflexbLzz/CLfYMLpsnYjkbtFvl9Vr0okOZ/Z58r/98= user@jenkins
