datasource:
 Ec2:
  strict_id: false
ssh_pwauth: no
users:
  - name: user
    groups: sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDD0ZKZZdzDsN4NXBvfIW352xAgYr/HAdUXPLz3NvpyA0v71Ce4bBbv6K6QwYilElZtCFyt123fxsb5FQypbB/YOQO/ez9OT1yLX8coeJIN3fZGBX7vtnoodkkMlP+W/daev+rxeL2nKHaFyd2gBfnlFgx46Quo71+KQ2RDGaZjakb7NPlZR2QHK0ApWeyfg2RAigWvC8H4WpujvgTYeNuWpGy4iVsFEL5NULstbd0F/n/HAWEKA50ANWxpET1SfnQtik7sF26UpoKId67KCAZ/AC6pM1Iurca86eD1rh+mrGdZYOxUVR42IErIgE1Nw+w9kIJJ7IZN+kcMyv+wH20jU8NKWloIHOhbt360eUX7wY/F3+BnZevtNnHtTnSB4fGqU72A3/NgT7JHjfMAA7xCIFg3NI0TQNme/uUMw0QaCZ5jkjAOQO1CP3lAzTkJ6HPTC7/ab6zh5ke+W2lxS+LUVEof+CIsBGuU8Ry/WlneBs6yqRiZwqd2/N/r31wl1J0= root@jenkins
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKlkIigZ/ee23wpMoYGBY5oM8EnNlNpx27IwTBWCaVDUCt5bhLT/CrZ5UrR4Xc1ppGQWq06Sjt++rKBV199Z9IpSIyQKOP8Tdf5l4g6VMhUrqzwKIGWYZcbBdbMGN47+ODfcxxA8o1CZHIxz+EvetJs2UQakLp2Dsj8uLuxptCHqjx1KCXhJBQg3S0tP5Y54FzfvHA+fpFeg50DRxs3nNgKNskyhOL5PqWPHiUQzNcKLVzU+h0X/kAAbJDe1hmqN9mP2NbbjDoIw100AJHPGNCEcuxc7FEmHRQzN23exmhMK2a29YMtJ+yIjq5crWgHccoKiOkRFJ+jtRNtCaFdGOKPQXtD9EJUFgRBED1aguWLY6pT0Wt7/AeET97fwQzf+A9WGRU3SGlmINR+SsUxpQzNu+wnjZ2wNu84+3jeeLIjAD5oFqGjLzBt1hohyPp5JRYnp42kZTD64qgEaziXspbM2SGme+sVCqEhn/5oAOgvFeXbaFGCtb8YAW1En0FKb8= user@jenkins
